-- ==============================================================================
-- SCHEMA SUPABASE PARA GAMI-STUDIO / PSYCHOQUEST & MINDPULSE UDD
-- Puedes ejecutar este script en el SQL Editor de tu Dashboard de Supabase:
-- https://supabase.com/dashboard/project/oeymgclqslgvrqlhruty/sql
-- ==============================================================================

-- 1. Tabla para almacenar las sesiones de diagnóstico clínico (Aula / TCC)
CREATE TABLE IF NOT EXISTS clinical_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT DEFAULT 'estudiante_udd',
  score INT DEFAULT 0,
  accuracy INT DEFAULT 0,
  max_streak INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla para almacenar el estado y puntos del colaborador (Empresa / MindPulse)
CREATE TABLE IF NOT EXISTS user_zen_state (
  user_id TEXT PRIMARY KEY,
  zen_points INT DEFAULT 450,
  completed_tasks JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Habilitar políticas de acceso público / anónimo para demostración
ALTER TABLE clinical_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_zen_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura y escritura publica de sesiones clinicas"
  ON clinical_sessions FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Permitir lectura y escritura publica de estado zen"
  ON user_zen_state FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);
